# Generated by Django 3.1.6 on 2021-05-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20210510_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='', height_field=170, upload_to='', width_field=170),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
