# Generated by Django 3.1.6 on 2021-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20210510_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, height_field=170, upload_to='', width_field=170),
        ),
    ]
