# Generated by Django 3.2.3 on 2021-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='settings.MEDIA_ROOT/img/pfp.png', upload_to='img/'),
        ),
    ]
