# Generated by Django 3.2.3 on 2021-05-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_auto_20210526_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/posts/'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_vehicles',
        ),
        migrations.AddField(
            model_name='user',
            name='my_vehicles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_who_own', to='users_app.vehicle'),
        ),
    ]
