# Generated by Django 3.2.3 on 2021-05-28 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_auto_20210528_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_vehicles',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_vehicles', to='users_app.user'),
        ),
    ]
