# Generated by Django 3.2.3 on 2021-05-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0012_auto_20210528_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owned_by',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owned_by',
            field=models.ManyToManyField(related_name='users_vehicles', to='users_app.User'),
        ),
    ]
