# Generated by Django 3.2.3 on 2021-05-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0013_auto_20210528_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owned_by',
        ),
        migrations.AddField(
            model_name='user',
            name='vehicles_owned',
            field=models.ManyToManyField(related_name='owners', to='users_app.Vehicle'),
        ),
    ]
