# Generated by Django 3.2.3 on 2021-05-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0014_auto_20210528_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicles_owned',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owners',
            field=models.ManyToManyField(related_name='owned_vehicles', to='users_app.User'),
        ),
    ]
