# Generated by Django 3.2.3 on 2021-06-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0021_auto_20210601_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='chassis',
        ),
        migrations.AddField(
            model_name='thread',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='users_app.user'),
        ),
        migrations.AddField(
            model_name='thread',
            name='make',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='model',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='following_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users_app.user', unique=True),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users_app.user', unique=True),
        ),
    ]
