# Generated by Django 3.2.3 on 2021-06-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0025_alter_post_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
