# Generated by Django 3.2.3 on 2021-06-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0028_meet_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
