from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index),
    path('register', views.register),
    path('login', views.login),
    path('logout', views.logout),
    path('dashboard', views.dashboard),
    path('profile', views.displayMyProfile),
    path('submitpfp', views.updateProfile),
    path('meets', views.meets),
    path('discussions', views.discussionsHome),
    path('discussions/<int:id>', views.discussionPage),
    path('post', views.makePost),
    path("post/<int:id>/edit", views.displayEditPostForm),
    path("post/edit", views.editPost),
    path('deletePost/<int:id>', views.deletePost),
    path("likePost", views.likePost),
    path("users/<int:id>", views.displayUser),
    path("users/<int:id>/followUser", views.followUser),
    path("discussions/new", views.displayThreadForm),
    path("discussions/createThread", views.createThread),
    path("discussions/createPost", views.postToThread),
    path("discussions/<int:id>/editForm", views.displayUpdateThreadForm),
    path("discussions/<int:id>/update", views.updateThread),
    path("discussions/<int:id>/delete", views.deleteThread),
    path("meets/new", views.newMeetForm),
    path("meets/createMeet", views.createMeet),
    path("meets/delete/<int:id>", views.deleteMeet),
    path("meets/<int:id>", views.displayMeet),
    path("meets/findByState", views.meetsByState),
    path("meets/<int:id>/attendMeet", views.attendMeet),
]